#!/bin/bash

#  Copyright (C) 2015-2017  Rafael Senties Martinelli <rafael@senties-martinelli.com>
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.

echo "Enabling and starting systemd..."
if [ -f /bin/systemctl ]; then
    systemctl enable alienware-kbl
    systemctl start alienware-kbl
fi

echo "Linking the python bindings..."
if [ ! -d /usr/lib/python3 ]; then
    mkdir /usr/lib/python3
fi

if [ -d /usr/lib/python3 ]; then
    ln -s /usr/share/AlienwareKBL/Bindings.py /usr/lib/python3/AKBL.py
    echo "Python3 linked."
fi

if [ -d /usr/lib/python3.4 ]; then
    ln -s /usr/share/AlienwareKBL/Bindings.py /usr/lib/python3.4/AKBL.py
    echo "Python3.4 linked."
fi

if [ -d /usr/lib/python3.5 ]; then
    ln -s /usr/share/AlienwareKBL/Bindings.py /usr/lib/python3.5/AKBL.py
    echo "Python3.5 linked."
fi

if [ -d /usr/lib/python3.6 ]; then
    ln -s /usr/share/AlienwareKBL/Bindings.py /usr/lib/python3.6/AKBL.py
    echo "Python3.6 linked."
fi







