#!/bin/bash

#  Copyright (C) 2016-2018  Rafael Senties Martinelli
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.


if [ -f /bin/systemctl ]; then
	echo -e "\033[0;33mEnabling and starting systemd...\033[0m"
    systemctl enable akbl
    systemctl start akbl
else
	echo -e "\e[00;31m Warning: systemd seems to be missing. AKBL will not work.\e[00m"
fi

echo -e "\033[0;33mLinking python...\033[0m"

for python_version in "${AKBL_PYTHON_VERSIONS[@]}"; do
    if [ -d /usr/lib/$python_version ]; then
        ln -s /usr/lib/python3/AKBL /usr/lib/$python_version/AKBL && echo -e "\033[0;33m$python_version linked.\033[0m"
    fi
done
