#!/bin/bash

#  Copyright (C) 2016-2017  Rafael Senties Martinelli <rafael@senties-martinelli.com>
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.


#
# alienware-kbl doesn't includes `python-usb` anymore,
# this will prevent users from using the old `python-usb`.
#
if [ -d /usr/share/AlienwareKBL/usb ]; then
    rm -rf /usr/share/AlienwareKBL/usb
fi

echo "Saving possible configuration files from older versions..."
#
#  Move the themes from `/usr/share/` to `/etc/`  (in case of upgrading an older version of akbl)
#
if [ -d /usr/share/AlienwareKBL/Profiles ]; then

    if ! [ -d /etc/alienware-kbl ]; then
        mkdir /etc/alienware-kbl
    fi

    if ! [ -d /etc/alienware-kbl/profiles ]; then
        mkdir /etc/alienware-kbl/profiles
    fi

    cp -r /usr/share/AlienwareKBL/Profiles /etc/alienware-kbl/profiles
    rm -rf /usr/share/AlienwareKBL/Profiles
    
    echo "Profiles saved."
fi

#
#  Move the configuration file to /etc/         (in case of upgrading an older version of akbl)
#
if [ -f /usr/share/AlienwareKBL/config ]; then

    if ! [ -d /etc/alienware-kbl ]; then
        mkdir /etc/alienware-kbl
    fi

    cp /usr/share/AlienwareKBL/config /etc/alienware-kbl/alienware-kbl.ini
    rm -f /usr/share/AlienwareKBL/config
    
    echo "Configuration saved."
fi
