#!/bin/bash

#  Copyright (C) 2015-2018  Rafael Senties Martinelli
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.


if [ -f /bin/systemctl ]; then
	echo -e "\033[0;33mDisabling the systemd daemon...\033[0m"
    systemctl stop akbl
    systemctl disable akbl
fi

echo -e "\033[0;33mRemoving pyhon links...\033[0m"

python_versions=("python3.4" "python3.5" "python3.6" "python3.7" "python3.8" "python3.9")

for python_version in "${python_versions[@]}"; do
    if [ -f /usr/lib/$python_version/AKBL ]; then
        rm -f /usr/lib/$python_version/AKBL && echo -e "\033[0;33mlink removed from $python_version\033[0m"
    fi 
done
