#!/bin/bash

#  Copyright (C) 2015-2018  Rafael Senties Martinelli
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.

echo ""

if [ -f /bin/systemctl ]; then
	echo -e "\033[0;33m[OLD VERSION] Disabling the systemd daemon...\033[0m"
    systemctl stop alienware-kbl
    systemctl disable alienware-kbl
fi

echo -e "\033[0;33m[OLD VERSION] Removing the links to the python bindings...\033[0m"

for python_version in "${AKBL_PYTHON_VERSIONS[@]}"; do
    if [ -f /usr/lib/$python_version/AKBL.py ]; then
        rm -f /usr/lib/$python_version/AKBL.py && echo -e "\033[0;33m[OLD VERSION] link removed from $python_version\033[0m"
    fi 
done
