#!/bin/bash

#  Copyright (C) 2015-2018  Rafael Senties Martinelli
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.


if [ "$EUID" -ne 0 ]
  then echo "The script must be run as root."
  exit
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

if [ -f /bin/systemctl ]; then
	echo -e "\n\033[0;32mDisabling the systemd daemon...\033[0m"
    systemctl stop akbl
    systemctl disable akbl
    echo ""
fi

echo -e "\033[0;32mRemoving the software links..\033[0m"

AKBL_PYTHON_VERSIONS=("python3.1" "python3.2" "python3.3" "python3.4" "python3.5" "python3.6" "python3.7" "python3.8" "python3.9")

for python_version in "${AKBL_PYTHON_VERSIONS[@]}"; do

    if [ -f /usr/lib/$python_version/AKBL ] || [ -d /usr/lib/$python_version/AKBL ]; then
        rm -rf /usr/lib/$python_version/AKBL && echo -e "$python_version AKBL removed"
    fi 
    if [ -f /usr/lib/$python_version/AKBL.py ] || [ -d /usr/lib/$python_version/AKBL.py ]; then
        rm -rf /usr/lib/$python_version/AKBL.py && echo -e "$python_version AKBL.py removed"
    fi
    
done
echo ""



echo -e "\033[0;32mRemoving the software files and directories..\033[0m"


function remove_file(){
     
    if [ -f $1 ]; then
        rm -f $1
        echo "removed.f: $1"
    fi
}

function remove_dir(){
     
    if [ -d $1 ]; then
        rm -rf $1
        echo "removed.d: $1"
    fi
}

# for old versions "alienware-kbl.desktop"
remove_file "/usr/share/applications/alienware-kbl.desktop"
remove_file "/usr/bin/akbl"
remove_file "/usr/share/applications/AKBL.desktop"
remove_file "/usr/lib/systemd/system/AKBL.service"
remove_dir  "/usr/share/AKBL"
remove_dir  "/usr/share/doc/AKBL"
remove_dir  "/usr/lib/python3/AKBL"




if [ "$1" != "-s" ]; then
	echo -e "\e[00;32mAKBL has been removed.\e[00m"
fi
