#!/bin/bash

#  Copyright (C) 2015-2018  Rafael Senties Martinelli
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.


if [ "$EUID" -ne 0 ]
  then echo "[OLD VERSION] The script must be run as root."
  exit
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

./prerm-old

echo -e "\033[0;33m[OLD VERSION] Removing files and directories...\033[0m"
# Remove the new version of Alienware-KBL
#

if [ -d /usr/share/alienware-kbl ]; then
	rm -rf /usr/share/AlienwareKBL
fi

if [ -d /usr/share/doc/alienware-kbl ]; then
	rm -rf /usr/share/doc/AlienwareKBL
fi

# Remove the old version of Alienware-KBL
#

if [ -d /usr/share/alienware-kbl ]; then
	rm -rf /usr/share/alienware-kbl
fi

if [ -d /usr/share/doc/alienware-kbl ]; then
	rm -rf /usr/share/doc/alienware-kbl
fi

# Remove common files of both versions
#

if [ -f /usr/lib/systemd/system/alienware-kbl.service ]; then
	rm -rf /usr/lib/systemd/system/alienware-kbl.service
fi

if [ -f /usr/share/applications/alienware-kbl.desktop ]; then
	rm -f /usr/share/applications/alienware-kbl.desktop
fi

if [ -f /usr/bin/alienware-kbl ]; then
	rm -f /usr/bin/alienware-kbl
fi

if [ "$1" != "-s" ]; then
	echo -e "\e[00;32m[OLD VERSION] Alienware-KBL has been removed.\e[00m"
fi
