#!/bin/bash

#  Copyright (C) 2015-2016  Rafael Senties Martinelli <rafael AT senties-martinelli DOT com>
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR


if [ "$EUID" -ne 0 ]
  then echo "The script must be run as root."
  exit
fi

#
#
chmod -R 0755 $DIR
chown root:root -R $DIR
chmod 644 ./usr/lib/systemd/system/alienware-kbl.service

#
# These files shouldn't be shiped with the package,
# they are removed in case they've been forgotten
# at the source code.
#
if [ -d $DIR/usr/share/alienware-kbl/Profiles ]; then
	rm -rf $DIR/usr/share/alienware-kbl/Profiles
fi

if [ -d $DIR/usr/share/alienware-kbl/config ]; then
	rm -rf $DIR/usr/share/alienware-kbl/config
fi

if [ -d $DIR/usr/share/alienware-kbl/__pycache__ ]; then
	rm -rf $DIR/usr/share/alienware-kbl/__pycache__
fi

#
# Save the user configuration files
#
./preinst

#
# Remove previous versions
#
echo -e "\e[00;32mTo ensure a clean installation, the previous version will be fully removed..\e[00m"
./remove
echo -e "\e[00;32mThe installation will continue..\e[00m"

#
# Start the installation
#
echo -e "Copying the software files..."
cp -ar $DIR/usr/. /usr/

#
# Post installation
#
./postinst

echo -e "\e[00;32mAlienware-KBL is installed, enjoy the software !\e[00m"
