#!/bin/bash

#  Copyright (C) 2015-2017  Rafael Senties Martinelli <rafael@senties-martinelli.com>
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.


if [ "$EUID" -ne 0 ]
  then echo "The script must be run as root."
  exit
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR
chmod a+x ./remove ./prerm ./postinst

#
# These files shouldn't be shiped with the package,
# they are removed in case they've been forgotten
# in the source code.
#
if [ -d $DIR/usr/share/alienware-kbl/__pycache__ ]; then
	rm -rf $DIR/usr/share/alienware-kbl/__pycache__
fi

#
# Remove previous versions
#
echo -e "\e[00;32mTo ensure a clean installation any previous version will be fully removed..\e[00m"
./remove -s

#
# Start the installation
#
echo -e "\e[00;32mCopying the software files (the message 'ommiting directory' is normal)...\e[00m"
install -d /usr/share/alienware-kbl
install -D $DIR/usr/share/alienware-kbl/* /usr/share/alienware-kbl

install -d /usr/share/alienware-kbl/images
install -D $DIR/usr/share/alienware-kbl/images/* /usr/share/alienware-kbl/images

install -d /usr/share/applications
install -D $DIR/usr/share/applications/* /usr/share/applications

install -d /usr/share/doc/alienware-kbl
install -D $DIR/usr/share/doc/alienware-kbl/* /usr/share/doc/alienware-kbl

install -d /usr/bin
install -D $DIR/usr/bin/* /usr/bin

install -d /usr/lib/systemd/system
install -D $DIR/usr/lib/systemd/system/* /usr/lib/systemd/system

#
# Executing the post-installation script
#
echo -e "\e[00;32mExecuting the post-installation...\e[00m"
./postinst

echo -e "\e[00;32mAlienware-KBL is installed, enjoy it !\e[00m"
