#!/bin/bash

#  Copyright (C) 2015  Rafael Senties Martinelli <rafael@senties-martinelli.com>
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.

if [ -f /bin/systemctl ]; then
	systemctl stop alienware-kbl
	systemctl disable alienware-kbl
fi

if [ -f /usr/lib/python3/AlienwareKBL.py ]; then
	rm -f /usr/lib/python3/AlienwareKBL.py
fi 

if [ -f /usr/lib/python3.4/AlienwareKBL.py ]; then
	rm -f /usr/lib/python3.4/AlienwareKBL.py
fi 

if [ -f /usr/lib/python3.5/AlienwareKBL.py ]; then
	rm -f /usr/lib/python3.5/AlienwareKBL.py
fi 

if [ -d /usr/share/alienware-kbl/__pycache__ ]; then
	rm -rf /usr/share/alienware-kbl/__pycache__
fi 
